cart/urls.py
from django.urls import path

from cart import views

app_name = 'cart'

urlpatterns = [
    path('order-summary/', views.order_details, name='order_summary'),
    path('add-to-cart/<int:prod_id>/', views.add_to_cart, name='add_to_cart'),
    path('get_user_details/', views.get_user_details, name='get_user_details'),
    path('delete-from-cart/<int:item_id>/', views.delete_from_cart, name='delete_from_cart'),
    path('checkout/', views.checkout, name='checkout'),
    path('update_transaction_records/', views.update_transaction_records, name='update'),
    path('qtyupdate/', views.qtyupdate, name='qtyupate'),
]

customer/urls.py
from django.urls import path, include
from customer import views
from django.conf.urls import url
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, \
    PasswordResetCompleteView

app_name = 'customer'

urlpatterns = [
    path('home/', views.list_categories, name='home'),
    url(r'^review/(?P<categ>\w+)/(?P<product>\w+)/$', views.reviewtext, name='review'),
    path('home/<int:pk>/', views.itemsview, name='items'),
    path('home/<int:pk>/<int:ck>/', views.itemdetailview, name='specificitem'),
    path('authentication/', include('actor_authentication.urls')),
    path('search_results/', views.Search_Results, name="search_results"),
    path('faq/', views.faq, name='faq'),
    path('about-us/', views.about_us, name='about_us'),
    path('profile/', views.profile, name='profile'),
    path('password_reset/', PasswordResetView.as_view(), name='forgot_pass'),
    path('password_reset_done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password_reset_confirm/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset_complete/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('QrCode/<int:id>/', views.QrCode, name="QrCode"),

    path('get_details/', views.get_details, name='get_tournament_details'),
    path('join_tournament/<int:pk>/', views.join_tournament, name='join_tournament'),
    path('show_products_api/', views.show_products_api),
]

show_products/urls.py
"""ASE1 URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.1/topics/http/urls/
Examples:
Function view
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from customer.views import list_categories

urlpatterns = [
    path('', list_categories, name='list_categories'),
    path('vendor/', include('vendor.urls')),
    path('customer/', include('customer.urls')),
    path('cart/', include('cart.urls')),
    path('customer/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]

# if settings.DEBUG:
#     urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

customer/models.py
from django.forms import ValidationError
from django.db import models
from django.contrib.auth.models import User
from vendor.models import Product
from django.db.models.signals import post_save


def phone_number_validation(ph_num):
    if len(str(ph_num)) != 10:
        raise ValidationError('The phone number must have 10 digits only')
    elif ph_num < 0:
        raise ValidationError('The phone number must be positive')


class CustomerProfile(models.Model):
    Customer = models.OneToOneField(User, on_delete=models.CASCADE, related_name='cus')
    prod = models.ManyToManyField(Product, blank=True)
    phone_number = models.IntegerField(null=True, validators=[phone_number_validation])
    address = models.TextField(null=True)

    def __str__(self):
        return self.Customer.username


def post_save_customerprofile_create(sender, instance, created, *args, **kwargs):
    if created:
        CustomerProfile.objects.get_or_create(Customer=instance)


post_save.connect(post_save_customerprofile_create, sender=User)

customer/forms.py
from django import forms
from django.contrib.auth.models import User
from customer.models import CustomerProfile


class TournamentJoin(forms.Form):
    name = forms.CharField(max_length=100)
    # tournament_name = forms.CharField(max_length=100)
    email = forms.EmailField()
    phone_number = forms.IntegerField(required=False)


class Contact_Form(forms.ModelForm):
    class Meta:
        model = CustomerProfile
        fields = ['phone_number', 'address']


class UpdateProfile(forms.ModelForm):
    class Meta:
        model = User
        fields = (
            'username',
            'first_name',
            'last_name',
            'email',
        )


class CustomerCreationForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(
        attrs={'placeholder': 'Enter Password Here ...'}))
    confirm_password = forms.CharField(widget=forms.PasswordInput(
        attrs={'placeholder': 'Confirm Password ...'}))

    class Meta:
        model = User
        fields = (
            'username',
            'first_name',
            'last_name',
            'email',
        )

    def clean_confirm_password(self):
        password = self.cleaned_data.get('password')
        confirm_password = self.cleaned_data.get('confirm_password')
        if password != confirm_password:
            raise forms.ValidationError('Password mismatch')
        return confirm_password

    def clean_email(self):
        email = self.cleaned_data.get('email')
        user = User.objects.get(email=email)
        if user:
            raise forms.ValidationError('Email Already Exists')
        return user

customer/views.py
from django.contrib.auth.models import User
from django.db.models import Q
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, logout
from customer.forms import CustomerCreationForm, Contact_Form, UpdateProfile
from vendor.models import Category, Product, Review, VendorProfile, VendorQty
from vendor.forms import writereview
from cart.models import Order
from customer.models import CustomerProfile
from django.contrib.auth.decorators import login_required

import requests, json
from customer.forms import TournamentJoin

api_key = 'GQIJ8cdB0aqCVM7y449lNgsquxP2w6'


def get_user_order(request):
    user_profile = get_object_or_404(CustomerProfile, Customer=request.user)
    ord = Order.objects.filter(owner=user_profile, is_ordered=True)
    if ord.exists():
        return ord
    return 0


def index(request):
    return render(request, 'customer/base.html')


def QrCode(request, id):
    This_Order = get_object_or_404(Order, id=id)
    string = This_Order.get_qr_code()
    context = {
        "string": string,
    }
    return render(request, "customer/QrCode.html", context)


@login_required
def profile(request):
    a = request.user
    # print(a)
    customer = CustomerProfile.objects.get(Customer=a)
    if request.method == 'POST':
        form = UpdateProfile(request.POST, instance=a)
        ContactForm = Contact_Form(request.POST, instance=customer)
        if form.is_valid() and ContactForm.is_valid():
            PhNo = ContactForm.cleaned_data.get('phone_number')
            addr = ContactForm.cleaned_data.get('address')
            user = form.save(commit=False)
            user.save()

            customer.phone_number = PhNo
            customer.address = addr
            customer.save()
            return redirect('customer:home')
    else:
        form = UpdateProfile(instance=request.user)
        ContactForm = Contact_Form(instance=customer)
        placed_order = get_user_order(request)
        context = {
            'form': form,
            'ContactForm': ContactForm,
            'ordre': placed_order
        }
        return render(request, 'customer/profile.html', context)


def itemsview(request, pk):
    categories = Category.objects.all()
    cat = Category.objects.get(id=pk)
    current_order_products = []
    if request.user.is_authenticated:
        filtered_orders = Order.objects.filter(owner=request.user.cus, is_ordered=False)
        if filtered_orders.exists():
            user_order = filtered_orders[0]
            user_order_items = user_order.items.all()
            current_order_products = [product.product for product in user_order_items]

    context = {
        'categories': categories,
        'cat': cat,
        'current_order_products': current_order_products
    }

    return render(request, "customer/items.html", context)


def Search_Results(request):
    products = []
    current_order_products = []
    query = request.GET.get('q')
    # print(query)
    if query:
        products = Product.objects.filter(
            Q(prod_name__icontains=query) |
            Q(brand__icontains=query) |
            Q(category__cat_name__contains=query)
        )
    if request.user.is_authenticated:
        filtered_orders = Order.objects.filter(owner=request.user.cus)
        if filtered_orders.exists():
            user_order = filtered_orders[0]
            user_order_items = user_order.items.all()
            current_order_products = [product.product for product in user_order_items]
    context = {
        "products": products,
        "current_order_products": current_order_products,
    }
    return render(request, 'customer/search_results.html', context)


def list_categories(request):
    url = 'http://127.0.0.1:8000/shopping/categories_list/?api_key=' + api_key
    response = requests.get(url)
    categories = response.json()

    for category in categories:
        if not Category.objects.filter(cat_name=category['cat_name']).exists():
            c = Category.objects.create(cat_name=category['cat_name'])
            c.save()

    url = 'http://127.0.0.1:8000/shopping/product_list/?api_key=' + api_key
    response = requests.get(url)
    products = response.json()

    for product in products:
        c = Category.objects.get(cat_name=product['category'])
        if not Product.objects.filter(category=c, prod_name=product['prod_name']).exists():
            p = Product.objects.create(category=c, prod_name=product['prod_name'],
                                       description=product['description'],
                                       stock=product['stock'], cost=product['cost'],
                                       brand=product['brand'])
            p.save()

            u = User.objects.get(username='sportshub')
            vendor = VendorQty.objects.get_or_create(Vendor=u, product=p)[0]
            vendor.qty = product['stock']
            vendor.save()
        else:
            u = User.objects.get(username='sportshub')
            instance = Product.objects.get(category=c, prod_name=product['prod_name'])
            vendor = VendorQty.objects.get_or_create(Vendor=u, product=instance)[0]
            vendor.qty = product['stock']
            vendor.save()
    all_categories = Category.objects.all()
    is_vendor = False
    if request.user.is_authenticated:
        try:
            vendor = request.user.vendorprofile
            is_vendor = True
        except:
            pass
    context = {
        "is_vendor": is_vendor,
        'categories': all_categories,
    }
    return render(request, 'customer/index.html', context)


def customer_signup(request):
    if request.method == 'POST':
        form = CustomerCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            contact_number = form.cleaned_data['contact_number']
            c = CustomerProfile.objects.get(Customer=user)
            c.phone_number = contact_number
            login(request, user)
            return redirect('customer:home')
    else:
        form = CustomerCreationForm()
    return render(request, 'customer/signup.html', {'form': form})


def customer_login(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('customer:home')
    else:
        form = AuthenticationForm
    return render(request, 'customer/login.html', {'form': form})


@login_required
def customer_logout(request):
    logout(request)
    return render(request, 'customer/logout.html')


def forgot_pass(request):
    return render(request, 'registration/password_reset_form.html')


def itemdetailview(request, pk, ck):
    categories = Category.objects.all()
    cat = Category.objects.get(id=pk)
    prod = Product.objects.get(id=ck)
    products = Product.objects.filter(category=cat)
    all_vendors = VendorQty.objects.filter(product=prod)
    current_order_products = []
    if request.user.is_authenticated:
        filtered_orders = Order.objects.filter(owner=request.user.cus, is_ordered=False)
        if filtered_orders.exists():
            user_order = filtered_orders[0]
            user_order_items = user_order.items.all()
            current_order_products = [product.product for product in user_order_items]
    context = {
        'categories': categories,
        'cat': cat,
        'prod': prod,
        'vendors': all_vendors,
        'current_order_products': current_order_products,
    }
    return render(request, "customer/itemdetail.html", context)


def faq(request):
    return render(request, 'customer/faqs.html')


def about_us(request):
    return render(request, 'customer/about_us.html')


@login_required
def reviewtext(request, categ, product):
    prod = get_object_or_404(Product, pk=product)
    cat = get_object_or_404(Category, pk=categ)
    if request.method == 'POST':
        form = writereview(request.POST)
        if form.is_valid():
            content = request.POST.get('content')
            rating = request.POST.get('rating')
            review1 = Review.objects.create(category=cat, product=prod, customer=request.user, content=content,
                                            rating=rating)
            review1.save()
            return redirect('/customer/home/' + str(categ) + '/' + str(product) + '/')
    else:
        form = writereview()
    return render(request, 'customer/writereview.html', {'form': form})


def get_details(request):
    url = 'http://127.0.0.1:8000/api/tournaments/'
    response = requests.get(url)

    tournaments = response.json()
    return render(request, 'customer/get_details.html', {'tournaments': tournaments})


def join_tournament(request, pk):
    if request.method == 'POST':
        form = TournamentJoin(request.POST)
        if form.is_valid():
            url = 'http://127.0.0.1:8000/api/tournaments_join/'
            k = request.POST['pk']
            name = form.cleaned_data['name']
            email = form.cleaned_data['email']
            if form.cleaned_data['phone_number']:
                phone_num = form.cleaned_data['phone_number']
                data = json.dumps({'name': name, 'tournament': k, 'mail': email, 'phoneNumber': phone_num})
                requests.post(url=url, data=data)

            else:
                data = json.dumps({'name': name, 'tournament': k, 'mail': email})
                requests.post(url=url, data=data)
            return redirect('customer:get_tournament_details')

        else:
            print('form is invalid')
            print(form.errors)
    else:
        form = TournamentJoin()

    # print(int(pk))

customer/templates/customer/QrCode.html
{% load static %}
{% load qr_code %}
<!DOCTYPE html>
<html>
<head>
<title>QrCode</title>
<body>
    {% qr_from_text string size="T" %}
</body>
</html>

customer/templates/customer/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
<title>Grocery Store</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"><link rel="stylesheet" type="text/css" href="{% static 'customer/css/review.css' %}" >
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false);
		function hideURLbar(){ window.scrollTo(0,1); } </script>
<link href="{% static 'customer/css/bootstrap.css' %}" rel="stylesheet" type="text/css" media="all" />
<link href="{% static 'customer/css/style.css' %}" rel="stylesheet" type="text/css" media="all" />
<link href="{% static 'customer/css/font-awesome.css' %}" rel="stylesheet" type="text/css" media="all" />
<!-- //font-awesome icons -->
<script src="https://code.jquery.com/jquery-3.3.1.min.js"
        integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
        crossorigin="anonymous"></script>
<script src="{% static 'customer/js/jquery-1.11.1.min.js' %}"></script>
<!-- //js -->
<link href='//fonts.googleapis.com/css?family=Ubuntu:400,300,300italic,400italic,500,500italic,700,700italic' rel='stylesheet' type='text/css'>
<link href='//fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,600,600italic,700,700italic,800,800italic' rel='stylesheet' type='text/css'>
<!-- start-smoth-scrolling -->
<script type="text/javascript" src="{% static 'customer/js/move-top.js' %}"></script>
<script type="text/javascript" src="{% static 'customer/js/easing.js' %}"></script>
<link rel="stylesheet" href="{% static 'customer/css/flexslider.css' %}" type="text/css" media="screen"
                  property=""/>
<script type="text/javascript">
	jQuery(document).ready(function($) {
		$(".scroll").click(function(event){
			event.preventDefault();
			$('html,body').animate({scrollTop:$(this.hash).offset().top},1000);
		});
	});
</script>
<!-- start-smoth-scrolling -->
{% block style %}
    {% endblock %}
</head>

<body>
<!-- header -->
	<div class="header">
		<div class="offers">
            {% if user.is_authenticated %}
			<a>Hi, Welcome {{ user.username }} !</a>
            {% else %}
            <a>Hi, Welcome Today !</a>
            {% endif %}
		</div>

		<div class="search">
			<form action="{% url 'customer:search_results' %}">
				<input type="text" name="q" placeholder="Search a product..." onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Search a product...';}" required="">
				<input type="submit" value=" " name="search_button">
			</form>
		</div>
		<div class="product_list_header">
			<form action="{% url 'cart:order_summary' %}" method="post" class="last">
				{% csrf_token %}
                <fieldset>
                    {% if user.is_authenticated %}
                        <input type="submit" name="submit" value="View your cart" class="button" />
                    {% endif %}
                </fieldset>
            </form>
		</div>
		<div class="header_right">
			<ul>
				<li class="dropdown profile_details_drop">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user" aria-hidden="true"></i></a>
					<div class="mega-dropdown-menu">
						<div class="vegetables">
							<ul class="dropdown-menu drp-mnu">
                                {% if user.is_authenticated %}
                                    <li><a href="{% url 'customer:actor_authentication:logout' %}">Logout</a></li>
                                    <li><a href="{% url 'customer:profile' %}">UserProfile</a></li>
                                    {% if is_vendor %}
                                        <li><a href="{% url 'vendor:view_products' %}">View Products</a></li>
                                    {% endif %}
                                {% else %}
                                    <li><a href="{% url 'customer:actor_authentication:login_all' %}">Login</a></li>
                                    <li><a href="{% url 'customer:actor_authentication:signup_all' %}">Sign Up</a></li>
                                {% endif %}
							</ul>
						</div>
					</div>
				</li>
			</ul>
		</div>
		<div class="header_right1">
			<h2><a href="{% url 'customer:home' %}">HOME</a></h2>
		</div>
		<div class="clearfix"> </div>
	</div>
<!-- script-for sticky-nav -->
	<script>
	$(document).ready(function() {
		 var navoffeset=$(".header").offset().top;
		 $(window).scroll(function(){
			var scrollpos=$(window).scrollTop();
			if(scrollpos >=navoffeset){
				$(".header").addClass("fixed");
			}else{
				$(".header").removeClass("fixed");
			}
		 });

	});
	</script>
<!-- //script-for sticky-nav -->
	<div class="logo_products">
		<div class="container" style="margin-left: 550px;">
			<div class="logo_products_left">
				<h1><a><span>Shopping</span> Store</a></h1>
			</div>
			<div class="clearfix"> </div>
		</div>
	</div>
<!-- //header -->
<!-- banner -->
<div class="banner"></div>


{% block content %}

{% endblock %}


<!-- footer -->
	<div class="footer">
		<div class="container" style="margin-left: 187px;">
			<div class="col-md-3 footer_grid">
				<h3>information</h3>
				<ul class="footer_grid_list">
					<li><a href="{% url 'customer:about_us' %}">About Us</a></li>
			</div>
			<div class="col-md-3 footer_grid">
				<h3>policy info</h3>
				<ul class="footer_grid_list">
                    <li><a href="{% url 'customer:faq' %}">FAQ's</a></li>
				</ul>
			</div>
{#			<div class="col-md-3 footer_grid">#}
{#				<h3>Get in Touch</h3>#}
{#				<ul class="footer_grid_list">#}
{#                    <li><a href="{% url 'blog:post_list' %}">Blog</a></li>#}
{#				</ul>#}
{#			</div>#}
			<div class="clearfix"> </div>
			<div class="footer_grids">
				<div class="col-md-3 footer_grid footer_grids_footer">
					<div class="footer_grid_bottom">
						<h5>connect with us</h5>
						<ul class="social_icons">
                            <li><a href="https://www.github.com/jiteshm17/ASE1_Clean" class="fa-github"><i class="fa fa-github" aria-hidden="true"></i></a></li>
							<li><a href="https://www.facebook.com" class="facebook"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
							<li><a href="https://www.google.com" class="google"><i class="fa fa-google-plus" aria-hidden="true"></i></a></li>

						</ul>
					</div>
				</div>
				<div class="clearfix"> </div>
			</div>
		</div>
	</div>
<!-- //footer -->
<!-- Bootstrap Core JavaScript -->
<script src="{% static 'customer/js/bootstrap.min.js' %}"></script>
<script>
$(document).ready(function(){
    $(".dropdown").hover(
        function() {
            $('.dropdown-menu', this).stop( true, true ).slideDown("fast");
            $(this).toggleClass('open');
        },
        function() {
            $('.dropdown-menu', this).stop( true, true ).slideUp("fast");
            $(this).toggleClass('open');
        }
    );
});
</script>
<!-- here stars scrolling icon -->
	<script type="text/javascript">
		$(document).ready(function() {
			/*
				var defaults = {
				containerID: 'toTop', // fading element id
				containerHoverID: 'toTopHover', // fading element hover id
				scrollSpeed: 1200,
				easingType: 'linear'
				};
			*/

			$().UItoTop({ easingType: 'easeOutQuart' });

			});
	</script>
<!-- //here ends scrolling icon -->

</body>
{% block scripts %}
{% endblock %}
</html>

customer/templates/customer/itemdetail.html
{% extends 'customer/base.html' %}
{% load static %}

{% block scripts %}
    <script>
        $(".cart-add").click(function () {
            let span = $(this).parent();
            var vendorid = parseInt(document.getElementById("select_vendor").value)
            console.log(vendorid);
            $.ajax({
                url: span.attr("add_url"),
                data: {vendorid: vendorid},
                {#success: function (response) {#}
                {#    console.log("finished", response);},#}
                {#error: function (xhr, textStatus, errorThrown) {#}
                {#    $.ajax({#}
                {#        url: '/customer/authentication/login/',#}
                {#        data:{vendorid:vendorid,next:span.attr("add_url"),nextto:span.attr("nextto")}#}
                {#    })}#}

            });
            {% if user.is_authenticated %}
                $(this).remove();
                $(span).append($('<a/>')
                    .attr('href', "{% url 'cart:order_summary'%}")
                    .attr('style', "background-color: #84C639;color:white;font-weight:bold;")
                    .addClass("btn btn-warning")
                    .text("Go to Cart"));
            {% else %}
                window.location.replace('/customer/authentication/login/?next=' + span.attr("add_url") + '&nextto=' + span.attr("nextto") + '&vendorid=' + vendorid)
            {% endif %}
        });
    </script>
{% endblock %}

{% block content %}
    <br>
    <div style="font-size: large;">
        <div class="collapse navbar-collapse" id="bs-megadropdown-tabs" style="width:20%;float: left;">
            <ul class="nav navbar-nav nav_1">
                {% for cat in categories %}
                    <li><a href={% url 'customer:items' cat.id %}><h3>{{ cat.cat_name }}</h3></a></li>
                {% endfor %}
            </ul>
        </div>
        <div style="padding-left:15%;margin-left:10%;">
            <h2 style="color:#FA1818;">{{ prod.prod_name }}</h2>
            <div style="display:inline-block;float:left;width:30%;padding-top: 4%;">
                {% if prod.prod_pic %}
                    <img src="{{ prod.prod_pic.path }}" width="300" height="300">
                {% endif %}
            </div>
            <div style="display: inline-block; width:60%;padding:8%;">
                <div style="font-size: large;">
                    Category:<b>{{ prod.category.cat_name }}</b><br><br>
                    {#                    <li>Stock: <b>{{ prod.stock }}</b></li>#}
                    Price: <b>{{ prod.cost }}</b><br><br>
                    {% if prod.brand|length > 0 %}
                        Brand: <b>{{ prod.brand }}</b><br><br>
                    {% endif %}
                    <br><br>
                    Choose your vendor&nbsp;
                    <select id="select_vendor">
                        {% for vendor in vendors %}
                            {% if vendor.qty > 0 %}
                                <option value="{{ vendor.id }}">{{ vendor.Vendor }}</option>
                            {% endif %}
                        {% endfor %}
                    </select>
                </div>
                {% if prod in current_order_products %}
                    <br><br>
                    <a class="btn btn-warning" href="{% url 'customer:review'  cat.id prod.id %}"
                       style="background-color: #FA1818;color:white;"><b>Write a review</b></a>
                    <a class="btn btn-warning cart-add" href="{% url 'cart:order_summary' %}"
                       style="background-color: #84C639;color:white;"><b>Go to Cart</b></a>
                {% else %}
                    <span id="prod_{{ prod.id }}" nextto="{% url 'customer:items' cat.id %}"
                          add_url="{% url 'cart:add_to_cart' prod.id %}">
                    <br><br>
                    <a class="btn btn-warning" href="{% url 'customer:review'  cat.id prod.id %}"
                       style="background-color: #FA1818;color:white;"><b>Write a review</b></a>
                    <a class="btn btn-warning cart-add"
                       style="background-color: #84C639;color:white;"><b>Add to Cart</b></a>

                {% endif %}
                </span>

            </div>
            <br>
            <div style="margin-bottom:4%;">
                <br>
                <h3 style="color:#FA1818;">Top Reviews:</h3>
                <br>
                <div style="padding-left: 4%;border: ">
                    <a name="review">
                        {% for review in prod.review_set.all %}
                            <p>{{ review.content }}</p>
                            <div class="star-rating">
                                <input id="star-5_{{ review.pk }}" type="radio" name="ratingnew_{{ review.pk }}"
                                       value="5"
                                       checked
                                       disabled>
                                <label for="star-5_{{ review.pk }}" title="5 stars">
                                    <i class="active fa fa-star" aria-hidden="true"></i>
                                </label>

                                <input id="star-4_{{ review.pk }}" type="radio" name="ratingnew_{{ review.pk }}"
                                       value="5"
                                       checked
                                       disabled>
                                <label for="star-4_{{ review.pk }}" title="5 stars">
                                    <i class="active fa fa-star" aria-hidden="true"></i>
                                </label>
                                <input id="star-3_{{ review.pk }}" type="radio" name="ratingnew_{{ review.pk }}"
                                       value="5"
                                       checked
                                       disabled>
                                <label for="star-3_{{ review.pk }}" title="5 stars">
                                    <i class="active fa fa-star" aria-hidden="true"></i>
                                </label>
                                <input id="star-2_{{ review.pk }}" type="radio" name="ratingnew_{{ review.pk }}"
                                       value="5"
                                       checked
                                       disabled>
                                <label for="star-2_{{ review.pk }}" title="5 stars">
                                    <i class="active fa fa-star" aria-hidden="true"></i>
                                </label>
                                <input id="star-1_{{ review.pk }}" type="radio" name="ratingnew_{{ review.pk }}"
                                       value="5"
                                       checked
                                       disabled>
                                <label for="star-1_{{ review.pk }}" title="5 stars">
                                    <i class="active fa fa-star" aria-hidden="true"></i>
                                </label>
                                <script>
                                    console.log($('input[name="ratingnew_{{ review.pk }}"]:radio'));
                                    $($('input[name="ratingnew_{{ review.pk }}"]:radio')[5 -{{ review.rating }}])
                                        .prop("checked", true);
                                </script>
                            </div>
                            <footer class="blockquote-footer">by <cite>{{ review.customer }}</cite></footer><br>
                        {% endfor %}
                    </a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}