cart/urls.py
from django.urls import path

from cart import views

app_name = 'cart'

urlpatterns = [
    path('order-summary/', views.order_details, name='order_summary'),
    path('add-to-cart/<int:prod_id>/', views.add_to_cart, name='add_to_cart'),
    path('get_user_details/', views.get_user_details, name='get_user_details'),
    path('delete-from-cart/<int:item_id>/', views.delete_from_cart, name='delete_from_cart'),
    path('checkout/', views.checkout, name='checkout'),
    path('update_transaction_records/', views.update_transaction_records, name='update'),
    path('qtyupdate/', views.qtyupdate, name='qtyupate'),
]

customer/urls.py
from django.urls import path, include
from customer import views
from django.conf.urls import url
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, \
    PasswordResetCompleteView

app_name = 'customer'

urlpatterns = [
    path('home/', views.list_categories, name='home'),
    url(r'^review/(?P<categ>\w+)/(?P<product>\w+)/$', views.reviewtext, name='review'),
    path('home/<int:pk>/', views.itemsview, name='items'),
    path('home/<int:pk>/<int:ck>/', views.itemdetailview, name='specificitem'),
    path('authentication/', include('actor_authentication.urls')),
    path('search_results/', views.Search_Results, name="search_results"),
    path('faq/', views.faq, name='faq'),
    path('about-us/', views.about_us, name='about_us'),
    path('profile/', views.profile, name='profile'),
    path('password_reset/', PasswordResetView.as_view(), name='forgot_pass'),
    path('password_reset_done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password_reset_confirm/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset_complete/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('QrCode/<int:id>/', views.QrCode, name="QrCode"),

    path('get_details/', views.get_details, name='get_tournament_details'),
    path('join_tournament/<int:pk>/', views.join_tournament, name='join_tournament'),
    path('show_products_api/', views.show_products_api),
]

show_products/urls.py
"""ASE1 URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.1/topics/http/urls/
Examples:
Function view
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from customer.views import list_categories

urlpatterns = [
    path('', list_categories, name='list_categories'),
    path('vendor/', include('vendor.urls')),
    path('customer/', include('customer.urls')),
    path('cart/', include('cart.urls')),
    path('customer/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]

# if settings.DEBUG:
#     urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models
from vendor.models import Product, VendorProfile
from customer.models import CustomerProfile
from django.contrib.auth.models import User


class OrderItem(models.Model):
    vendor = models.ManyToManyField(User)
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True)
    is_ordered = models.BooleanField(default=False)
    date_added = models.DateTimeField(auto_now_add=True)
    date_ordered = models.DateTimeField(null=True)
    qty = models.IntegerField(null=True, default=1)
    ref_code = models.CharField(max_length=20)

    def __str__(self):
        return self.product.prod_name

    def __unicode__(self):
        return '%s' % self.product.prod_name


class Order(models.Model):
    vendor = models.ManyToManyField(User)
    owner = models.ForeignKey(CustomerProfile, on_delete=models.SET_NULL, null=True, related_name='o')
    ref_code = models.CharField(max_length=20)
    items = models.ManyToManyField(OrderItem, related_name='item')
    is_ordered = models.BooleanField(default=False)
    date_ordered = models.DateTimeField(null=True)

    def get_cart_item(self):
        return self.items.all()

    def get_cart_total(self):
        return sum([item.product.cost * item.qty for item in self.items.all()])

    def get_qr_code(self):
        string = ""
        string += "Order Id :  " + str(self) + "\n"
        string += "For Mr/Mrs " + str(self.owner) + "\n"
        string += "Date Ordered :  " + str(self.date_ordered) + "\n\n"
        string += "Item : Quantity\n"
        for item in self.items.all():
            string += str(item.product.prod_name) + " : " + str(item.qty) + "\n"
        string += "Total is  :  ₹" + str(self.get_cart_total()) + "\n"
        string += "\nThank You"
        # print(string)
        return string

    def __str__(self):
        return '{0} -- {1}'.format(self.owner, self.ref_code)


class Transaction(models.Model):
    profile = models.ForeignKey(CustomerProfile, on_delete=models.CASCADE)
    order_id = models.CharField(max_length=120)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    success = models.BooleanField(default=True)
    timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)

    def __str__(self):
        return self.order_id

    class Meta:
        ordering = ['-timestamp']

cart/views.py
import datetime

import requests
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import send_mail, EmailMessage
from django.shortcuts import render, redirect, get_object_or_404, HttpResponse
from django.template.loader import render_to_string
from django.urls import reverse
from rest_framework.utils import json

from customer.views import api_key
from cart.extra import generate_order_id
from cart.models import OrderItem, Order, Transaction
from customer.forms import Contact_Form
from customer.models import CustomerProfile
from vendor.models import Product, VendorQty
from customer.views import api_key


def get_user_pending_order(request):
    user_profile = get_object_or_404(CustomerProfile, Customer=request.user)
    ord = Order.objects.filter(owner=user_profile, is_ordered=False)
    if ord.exists():
        return ord[0]
    return 0


@login_required(login_url='customer:actor_authentication:login_all')
def add_to_cart(request, prod_id):
    if request.GET:
        vendorid = request.GET['vendorid']
        # print(vendorid)
        ven_qty = VendorQty.objects.get(id=vendorid)
        ven = ven_qty.Vendor
        # print(ven)
        # print(ven_qty)

    user_profile = get_object_or_404(CustomerProfile, Customer=request.user)
    product = Product.objects.get(id=prod_id)

    user_order, status = Order.objects.get_or_create(owner=user_profile, is_ordered=False)

    if status:
        ref_code = generate_order_id()
        # print(ref_code)
        order_item, status = OrderItem.objects.get_or_create(product=product, ref_code=ref_code)
        order_item.vendor.add(ven)
        user_order.items.add(order_item)
        user_order.vendor.add(ven)
        user_order.ref_code = ref_code
        user_order.save()
    else:
        order_item, status = OrderItem.objects.get_or_create(product=product, ref_code=user_order.ref_code)
        order_item.vendor.add(ven)
        user_order.items.add(order_item)
        user_order.vendor.add(ven)
        user_order.save()

    if request.GET:
        nextto = request.GET["nextto"]
        return redirect(nextto)
    else:
        return HttpResponse('')


@login_required(login_url='customer:actor_authentication:login_all')
def delete_from_cart(request, item_id):
    item_to_delete = OrderItem.objects.filter(pk=item_id)
    if item_to_delete.exists():
        item_to_delete[0].delete()
    return redirect(reverse('cart:order_summary'))


@login_required(login_url='customer:actor_authentication:login_all')
def order_details(request, **kwargs):
    existing_order = get_user_pending_order(request)

    context = {
        'order': existing_order
    }
    return render(request, 'cart/order_summary.html', context)


@login_required(login_url='customer:actor_authentication:login_all')
def checkout(request, **kwargs):
    existing_order = get_user_pending_order(request)
    context = {
        'ordre': existing_order
    }

    return render(request, 'cart/checkout.html', context)


def get_user_details(request):
    u = CustomerProfile.objects.get(Customer=request.user)
    user_form = Contact_Form(instance=u)

    if request.method == 'POST':
        user_form = Contact_Form(request.POST, instance=u)
        if user_form.is_valid():

            order_to_purchase = get_user_pending_order(request)

            order_to_purchase.is_ordered = True
            order_to_purchase.date_ordered = datetime.datetime.now()

            customer = order_to_purchase.owner.Customer.username

            order_items = order_to_purchase.items.all()
            sportshub_order_items = []
            flag = 0
            url = 'http://127.0.0.1:8000/cart/get_logs/?api_key=' + api_key
            for item in order_items:
                ven = item.vendor.all()[0]
                # print('The vendor is', ven)
                if str(ven) == 'sportshub':
                    flag = 1
                    # print(ven)
                    print(request.user, item.product.prod_name, item.product.cost,
                          item.qty)

                    data = json.dumps(
                        {'user': request.user.username,
                         'product': item.product.prod_name,
                         'cost': item.product.cost,
                         'qty': item.qty
                         })
                    print('Data Sent')
                    print(requests.post(url=url, data=data))

                    sportshub_order_items.append({item.product.prod_name: item.qty})
                    # print(sportshub_order_items)
                ven_qty = VendorQty.objects.get(Vendor=ven, product=item.product)

                # print(ven_qty.qty)
                ven_qty.qty -= item.qty

                # print(ven_qty.qty)
                ven_qty.save()

            user_form = user_form.save()

            if len(sportshub_order_items) > 0:
                # print('An order has been placed')
                current_site = get_current_site(request)
                mail_subject = 'SportsHub Order Placed'
                message = render_to_string('cart/send_email.html', {
                    'domain': current_site.domain,
                    'user': customer,
                    'address': user_form.address,
                    'phone_number': user_form.phone_number,
                    'items': sportshub_order_items
                })
                email = EmailMessage(
                    mail_subject, message, to=[User.objects.get(username='sportshub').email]
                )
                email.send()

            order_items.update(is_ordered=True, date_ordered=datetime.datetime.now())

            transaction = Transaction(profile=request.user.cus,
                                      order_id=order_to_purchase.ref_code,
                                      amount=order_to_purchase.get_cart_total(),
                                      success=True)

            transaction.save()
            order_to_purchase.save()
            address = user_form.address
            phone_num = user_form.phone_number

            subject = 'Your order has been successfully placed'
            context = {
                'ordre': order_to_purchase,
                'user': request.user,
                'total': order_to_purchase.get_cart_total(),
                'address': address,
                'contact_details': phone_num,
                'ref_code': order_to_purchase.ref_code
            }
            html = render_to_string('cart/message.html', context)
            message = render_to_string('cart/message.html', context)
            email_from = settings.EMAIL_HOST_USER
            recipient_list = [request.user.email]

            send_mail(subject, message, email_from, recipient_list, fail_silently=False, html_message=html)
            messages.info(request, "Thank you! Your purchase was successful!")

            return render(request, 'cart/show_final_details.html', {'address': address,
                                                                    'phone_number': phone_num,
                                                                    'ref_code': order_to_purchase.ref_code})

    return render(request, 'cart/get_user_details.html', {'form': user_form})


@login_required(login_url='customer:actor_authentication:login_all')
def update_transaction_records(request):
    return redirect('cart:get_user_details')


def qtyupdate(request):
    a = request.POST.get('item_id')
    if request.method == "POST":
        order_id = request.POST["order_id"]
        item_id = request.POST["item_id"]
        qty = request.POST["z"]
        order = get_user_pending_order(request)
        item = order.items.get(pk=item_id)
        item.qty = qty
        # print("data: " + item_id + "        " + order_id + "           " + qty)
        item.save()
        order.save()
    return HttpResponse(" ")

cart/templates/cart/checkout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

cart/templates/cart/get_user_details.html
{% extends 'customer/base.html' %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit">
    </form>
{% endblock %}

cart/templates/cart/message.html
{% autoescape off %}
    Hi {{ user.username }}
    <table border="3">
        <tr>
            <th>s.no</th>
            <th>product</th>
            <th>quantity</th>
            <th>price</th>
        </tr>
        {% for item in ordre.get_cart_item %}

            <tr>
                <td>   {{ forloop.counter }}   </td>
                <td>   {{ item }}  </td>
                <td>{{ item.qty }}</td>
                <td> ₹{{ item.product.cost }}    </td>

            </tr>
        {% endfor %}
        <tr>
            <td colspan="3">Total</td>
            <td>{{ total }}</td>
        </tr>
    </table>
    <br>

    <h4>Your shipping address is {{ address }}</h4>
    <h4>Your order reference id is {{ ref_code }}</h4>

    <a href="http://127.0.0.1:8000/customer/QrCode/{{ ordre.id }}/" download="{{ ordre }}">Download QrCode</a><br>
    <a href="http://127.0.0.1:8000/customer/home">
        <button>Thank you for shopping with us</button>
    </a>
{% endautoescape %}

cart/templates/cart/order_summary.html
{% extends 'customer/base.html' %}
{% load customer_filters %}
{% block content %}
    <section>
        <div class="row">
            <table class="table table-hover table-bordered text-center">
                <thead class="thead-dark">
                <tr class="text-center">
                    <th>S.No</th>
                    <th>Item</th>
                    <th>Quantity</th>
                    <th>Price/per</th>
                    <th></th>

                </tr>
                </thead>
                {% for item in order.get_cart_item %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>
                            <strong>{{ item.product.prod_name }}
                            <span class="pull-right">
              <a href="{% url 'cart:delete_from_cart' item.id %}" data-balloon="remove this item from cart"
                 class="text-danger" onclick="return confirm_delete();">
                  <button type="button" class="btn btn-outline-danger btn-sm">Remove</button>
              </a>
                            </span></strong>
                        </td>
                        <td>
                            <select id="{{ item.id }}" onchange="mult(this)">
                                <option value="{{ item.qty }}" selected>{{ item.qty }}</option>
                                {% for i in item|get_qty_number %}
                                    <option value={{ i|add:1 }}>{{ i|add:1 }}</option>
                                {% endfor %}
                            </select>
                        </td>
                        <td><strong>₹{{ item.product.cost }}</strong></td>
                        <td><strong>₹<span id="get_price{{ item.id }}">{% multiply item.product.cost item.qty %}</span></strong></td>
                    </tr>
                {% empty %}
                    <tr>
                        <td colspan=4> You have not added any items yet.</td>
                    </tr>
                {% endfor %}
                <tr>
                    {% if order.get_cart_total != None %}
                        <td colspan=4>
                            <strong class="pull-right">Order Total:</strong>
                        </td>

                        <td colspan=2>
                            ₹<strong id="total">{{ order.get_cart_total }}</strong>
                        </td>
                    {% endif %}
                </tr>
                <tr>
                    <td colspan=2>
                        <a href="{% url 'customer:home' %}" class="btn btn-warning pull-left">
                            {% if order %}
                                Continue Shopping
                            {% else %}
                                Add Items to Cart
                            {% endif %}
                        </a>
                    </td>
                    <td colspan=3>
                        {% if order.get_cart_item %}
                            <a href="{% url 'cart:update' %}" class="pull-right btn btn-primary">Proceed To Checkout</a>
                        {% endif %}
                    </td>
                </tr>
            </table>

        </div>

    </section>
{% endblock %}
{% block scripts %}
    {{ block.super }}
    {% csrf_token %}
    <script>
        function confirm_delete() {
            return confirm("Do you want to remove this item from cart?");
        }

        function mult($this) {
            var x = 0, y = 0, z;
            z = $this.value
            {% for item in order.get_cart_item %}

                y = parseInt(document.getElementById("{{ item.id }}").value);
                x = x + {{item.product.cost}}*y;
                document.getElementById("get_price{{ item.id }}").innerHTML = ({{item.product.cost}}*y);
                {#$(#{{ item.id }}).html({{item.product.cost}}*y);#}
            {% endfor %}
            document.getElementById("total").innerHTML = x;
            var item_id = $this.id;
            var order_id = parseInt({{ order.id }});
            console.log("data: " + item_id + "        " + order_id + "           " + y);
            $.ajax({
                type: "POST",
                url: "{% url 'cart:qtyupate' %}",
                data: {item_id: item_id, order_id: order_id, z: z, csrfmiddlewaretoken: '{{ csrf_token }}'},
            })
        }

        $("button.add").on("click", function () {
            var tbody = $("table tbody");
            tbody.find("tr:eq(0)").clone().appendTo(tbody).find("input").val("");
        });
    </script>
{% endblock scripts %}

cart/templates/cart/send_email.html
{% load custom_filters %}

{% autoescape off %}
    An order has been placed by the user {{ user }}
    Address:{{ address }}
    PhoneNumber:{{ phone_number }}
    The items are as follows
    {% for item in items %}
        Item name :{{ item | get_item_name }}, qty is :{{ item | get_item_qty }}
    {% endfor %}
{% endautoescape %}

cart/templates/cart/show_final_details.html
{% extends 'customer/base.html' %}

{% block content %}
    <h3>Your order has been successfully placed</h3><br>
    <h4>Address {{ address }}</h4><br>
    <h4>Phone number {{ phone_number }}</h4><br>
    <h4>Your reference code is {{ ref_code }}</h4><br>

    <h4>We will send you an email shortly confirming you order<br>
        Thank you for shopping with us</h4>

{% endblock %}